
name: Unit/Module Tests for aivector Class

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash
    working-directory: ./build

jobs:
  tests_job:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      uses: actions/checkout@v4
    - name: Run cmake
      run: cmake --version
    - name: Run cmake2
      run: echo hello
    - name: Run cmake3
      run: echo come on


    # - uses: actions/checkout@v4
    # - run: cmake --version
